#!/bin/bash

case $1 in
    "-get" )    echo "getting newest infrared signal."
                curl -i "http://irkit****.local/messages" -H "X-Requested-With: curl"
                echo "done.";;
    "-send")    if [ 1 -lt $# ] ; then
                    echo "sending infrared signal."
                    curl -i "http://irkit****.local/messages" -H "X-Requested-With: curl" -d '${2}'
                    echo "done."
                else
                    echo "Invalid argument."
                fi;;
    *      )    echo "========== USEAGE =========="
                echo "<Type of command argument>"
                echo ""
                echo "-get"
                echo "get newest infrared signal from irkit."
                echo ""
                echo "-send"
                echo "send infrared signal of second argument to irkit."
                echo ""
                echo "-help"
                echo "display useage of this command."
                echo "";;
esac