#!/bin/bash

if [ $# -lt 1 ]; then
   exit 1
fi

META=`curl -s "http://${1}/keys" -d ''`
CLIENTKEY=${META:16:32}

echo "ClientKey =>"
echo ${CLIENTKEY}

META=`curl -s -d "clienttoken=${CLIENTKEY}" "https://api.getirkit.com/1/keys"`
DEVICEID=${META:13:32}
CLIENTKEY=${META:60:32}

echo "DeviceID  =>"
echo ${DEVICEID}

echo "ClientKey =>"
echo ${CLIENTKEY}
